### ISSUE TITLE
Switch to GitHub Actions

### ISSUE THREAD

**Issue by lkiesow** [opencast/pyCA#240]
[GitHub Actions](https://github.com/features/actions) is better integrated and faster than the currently used Travis CI. Switching would be nice.

**Comment by lkiesow** [comment]
The `.github/workflows/test.yml` should probably be something along the lines of:

```yml
name: Test PyCA

on:
  - push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.6
          - 3.7
          - 3.8

    steps:
    - name: install libgnutls28-dev
      run: |
        sudo apt update -q
        sudo apt install -q -y libgnutls28-dev libcurl4-gnutls-dev

    - uses: actions/checkout@v2

    - name: set up python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: install dependencies
      run: |
        pip install flake8 python-coveralls mock coverage
        pip install -r requirements.txt

    - name: lint
      run: make lint

    - name: test
      run: make test

```

…though it may make sense to switch [the GitHub Actions runner](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#github-hosted-runners) to `ubuntu-20.04` which isn't my favorite but may be the best choice right now.
